### PR TITLE
fix: casbin v2 support

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <c299999999@qq.com>

Fix: #1

### CODE REVIEW

**Comment by closetool** [comment]
@hsluoyz @kuchaguangjie @maxwellhertz plz review

**Review by hsluoyz — APPROVED** [review]
lgtm

**Comment by hsluoyz** [comment]
@maxwellhertz

**Comment by maxwellhertz** [comment]
Hi @closetool sorry I'm late. I've merged your pr already. Thanks for the fix! 😃

**Pull request merged**
